LIST_SEPARATOR = "|"
DEFAULT_SOURCE_PATH = "."
DEFAULT_TARGET_PATH = "build"
DEFAULT_TARGET_LANG = "en"
DEFAULT_LANGUAGES = ["en"]
DEFAULT_LC_MESSAGES = "en"
DEFAULT_BUILDERS = ["html"]
DEFAULT_TARGET_ORDER = "builder"
