# sphinxcli will use values from the project table as defined in PEP621
[project]
name = ""
version = ""
authors = [""]


[tool.sphinx]
project_copyright = ""
release = ""
requires-sphinx = "5.1.0"
nitpicky = false
logo = ""


[tool.sphinx.source]
root = "index"
encoding = "utf-8"
include = []
exclude = []
static = []
default_domain = ""
default_role = ""
warnings_keep = ""
warnings_suppress = ""

[tool.sphinx.source.suffixes]
".md" = "markdown"
".rst" = "rst"
".markdown" = "markdown"

[tool.sphinx.source.rst]
prolog = ""
epilog = ""

[tool.sphinx.source.markdown]
prolog = ""
epilog = ""

[tool.sphinx.tags]

[tool.sphinx.target]
directory = "build"
language = ["en", "fr"]           # or "en:fr" default is ["en"]
builders = ["html"]               # or "html" or "html:epub" default is html
subdirectories = "all | collapse"
theme = "furo"
# `all` always produces the folder structure `build/builder/language` even for a single builder and language
# `collapse` collapses a builders and languages as follows
#   builder = html, language = en -> build
#   builder = html, epub, language = en -> build/builder e.g. build/html
#   builder = html, language = en, fr -> build/language e.g. build/en, build/fr
#   builder = html, epub, language = en, fr -> sama as all e.g. build/html/en , build/html/fr, build/epub/en, build/epub/fr

[tool.sphinx.theme]
[tool.sphinx.theme.furo]
repo = "pradyunsg/furo"
announcement = ""
theme_light_logo = ""
theme_dark_logo = ""

[tool.sphinx.layout]
sidebars = []

[tool.sphinx.output]
add_function_parentheses = false
add_module_name = false
toc_object_entries_show_parents = ""
show_authors = false
modindex_common_prefix = []
trim_footnote_reference_space = "?"
trim_doctest_flags = true
strip_signature_backslash = false
emphasise_placeholders = false

# region builders
[tool.sphinx.builder.html]
theme = ""
encoding = "utf-8"
renderer = ""
title = ""
short_title = ""
logo = ""
favicon = ""
stylesheet = ""                # html_style
baseurl = ""
context = ""
css_files = []
js_files = []
static_path = []
extra_path = []
last_updated = ""
permalinks = true
permalinks_icon = ""
sidebars = []
additional_pages = {}
domain_specific_indices = true
use_index = true
split_index = false
copy_source = true
sourcelink_show = true
sourcelink_suffix = ""
use_opensearch = ""
file_suffix = ".html"
link_suffix = ""
show_copyright = true
show_search_summary = true
show_sphinx = true
compact_lists = true
section_number_suffix = ". "
search_language = ""
search_options = {}
search_scorer = ""

[tool.sphinx.builder.epub]
basename = ""
theme = ""
theme_options = ""
title = ""
description = ""
author = ""
contributor = ""
language = ""
publisher = ""
copyright = ""
identifier = ""
scheme = ""
uid = ""
cover = ""
css_files = ""
guide = ""

[tool.sphinx.builder.singlehtml]
sidebars = {}

[tool.sphinx.builder.htmlhelp]
basename = ""
file_suffix = ".html"
link_suffix = ".html"

[tool.sphinx.builder.applehelp]
version = ""
bundle_name = ""
bundle_id = ""
title = ""
icon = ""
dev_region = ""
kb_product = ""
kb_url = ""
remote_url = ""
index_anchors = ""
min_term_length = ""
stopwords = ""
locale = ""
codesign_identity = ""
codesign_flags = ""
indexer_path = ""
disable_external_tools = ""

[tool.sphinx.builder.man]
url = ""

# endregion builders

[tool.sphinx.highlighting]
langauge = "default"
theme = ""           # pygments_style

[[tool.sphinx.highlighting.options]]
name = ""
value = ""


[tool.sphinx.math]
number_figures = true          # numfig
number_all = false
equation_reference_format = ""

[tool.sphinx.i18n]
catalog_dir = ""
allow_fuzzy_translations = false
compact = false
generate_uuid = false
location = true
auto_build = true
additional_targets = []
figure_language_filename = ""

[tool.sphinx.figure]
add_number = true # numfig
format = ""       # numfig_format
secnum_depth = 0  # numfig_secnum_depth

[tool.sphinx.remote]
useragent = ""
tls_verify = true
tls_cacerts = ""

[tool.sphinx.smartquotes]
enabled = false
action = "qDe"

[tool.sphinx.smartquotes.excludes]
languages = []
builders = []
